### ISSUE TITLE
Stuck in encounter

### ISSUE THREAD

**Issue by amchugh** [amchugh/AB#1]
After winning an encounter on map ID 0, a new encounter with the same enemy is immediately generated with no chance to move to escape the region. Help.

**Comment by amchugh** [comment]
After doing some thinking about it, I predict the problem has to do with the shouldScenePush method in ASceneMap (names may be slightly off). I think the method is consulted for whether the scene should push, but that value isn't cleared once it's consumed by GameMain, meaning the next time it asks it receives the same value from the map. A mechanism should be added (or implemented if the framework exists) to clear the "shouldScenePush" value once it's used.

**Comment by mchughj** [comment]
Actually this is my bug!  It turns out that the encounter scene completes, we return to the map, you are still in the region where you may have another encounter, we randomly determine that you should have one and it starts all over again!  I will have to change this so that you cannot have another encounter within the same region until you exit and then re-enter it!  :)

**Comment by mchughj** [comment]
Fixed by https://github.com/amchugh/AB/bbd68b5e660781085bd2525e8767cff9898b4133.
